[project]
name = "llm-chat-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
    "notebook>=7.4.7",
    "llama-cpp-python>=0.2.90",
    "huggingface-hub>=0.26.0",
]
